### ISSUE TITLE
Certificate errors in `Data/SIPP/download_NBER_all.sh`

### ISSUE THREAD

**Issue by sbarkerECON** [tyleransom/EER_CWP#1]
All .dct and .zip files fail to download due to authentication errors. When run, the wget error messages recommend the ```--no-check-certificate``` option to connect insecurely. Adding this option before the ```-O``` option does indeed make the download work.

**Comment by tyleransom** [comment]
Thanks for letting me know. I will update the shell script accordingly and close this when I've done so.

**Comment by tyleransom** [comment]
It looks like this is a problem with NBER's URL having changed. replacing `http://www` with `https://data` in the URLs fixes the issue. That is a better solution than using `--no-check-certificate`. cc: @jaredashworth.

**Comment by tyleransom** [comment]
@sbarkerECON thanks for bringing this to our attention!

**Comment by sbarkerECON** [comment]
Thank you for the fix and for making your code so easily accessible--it's been very helpful!
